In [1]:
import pandas as pd
import numpy as np

In [10]:
data = pd.read_fwf("GP208_HW1_Barnett_Density_Log.txt",sep="\t")

In [11]:
data.columns=["depth", "rho"]

In [12]:
data

                depth  rho
0          95\t1.8778  NaN
1        95.5\t1.8778  NaN
2          96\t1.8778  NaN
3        96.5\t1.8778  NaN
4          97\t1.8778  NaN
5        97.5\t1.8778  NaN
6          98\t1.8778  NaN
7        98.5\t1.8778  NaN
8          99\t1.8778  NaN
9        99.5\t1.8778  NaN
10        100\t1.8778  NaN
11      100.5\t1.8778  NaN
12        101\t1.8709  NaN
13      101.5\t1.8317  NaN
14        102\t1.8363  NaN
15        102.5\t1.85  NaN
16        103\t1.8441  NaN
17      103.5\t1.8299  NaN
18        104\t1.8303  NaN
19      104.5\t1.8555  NaN
20        105\t1.8603  NaN
21      105.5\t1.8491  NaN
22        106\t1.8387  NaN
23      106.5\t1.8514  NaN
24        107\t1.8729  NaN
25      107.5\t1.8746  NaN
26        108\t1.8667  NaN
27      108.5\t1.8845  NaN
28        109\t1.8826  NaN
29      109.5\t1.8585  NaN
...               ...  ...
12168    6179\t2.0899  NaN
12169  6179.5\t2.0869  NaN
12170    6180\t2.0695  NaN
12171  6180.5\t2.0843  NaN
12172    6181\t2.0974  NaN
12173  6181.5\t2.1225  NaN
12174    6182\t2.1057  NaN
12175  6182.5\t2.0815  NaN
12176    6183\t2.0808  NaN
12177  6183.5\t2.0315  NaN
12178    6184\t2.0565  NaN
12179  6184.5\t2.0624  NaN
12180    6185\t2.0648  NaN
12181   6185.5\t2.065  NaN
12182     6186\t2.065  NaN
12183   6186.5\t2.065  NaN
12184     6187\t2.065  NaN
12185   6187.5\t2.065  NaN
12186     6188\t2.065  NaN
12187   6188.5\t2.065  NaN
12188     6189\t2.065  NaN
12189   6189.5\t2.065  NaN
12190    6190\t2.0651  NaN
12191  6190.5\t2.0653  NaN
12192    6191\t2.0663  NaN
12193  6191.5\t2.0703  NaN
12194    6192\t2.0857  NaN
12195  6192.5\t2.1434  NaN
12196    6193\t2.3314  NaN
12197  6193.5\t2.6056  NaN

[12198 rows x 2 columns]